name: tex-fmt
on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }}
    - name: Run tex-fmt
      uses: grayespinoza/tex-fmt-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args:
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@master
      with:
        commit_message: "Formatted using tex-fmt"
